#!/bin/sh

# tell i3bar to use json
echo '{"version": 1}'
echo '['
# make the loop simpler
echo '[],'

if [ -f "$HOME/.i3/conkyrc.local" ]; then
    exec conky -c "$HOME/.i3/conkyrc.local"
else
    exec conky -c "$HOME/.i3/conkyrc"
fi
